version: '3.9'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"  # Le port 8080 du conteneur est exposé sur la machine hôte
    volumes:
      - ./frontend:/usr/share/nginx/html  # Le code source du frontend est partagé entre la machine hôte et le conteneur
    networks:
      - hackathon_network

  backend:
    build: ./backend
    ports:
      - "5001:5001"  # Le port 5001 du conteneur est exposé sur la machine hôte
    depends_on:
      - db  # Ce service attend que le service db démarre avant de se lancer
    volumes:
      - ./backend:/app  # Le code source du backend est partagé entre la machine hôte et le conteneur
    networks:
      - hackathon_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root  # Définit le mot de passe pour l'utilisateur root
      MYSQL_DATABASE: hackathon  # La base de données hackathon est créée au démarrage
    ports:
      - "3306:3306"  # Le port 3306 (par défaut pour MariaDB) est exposé sur la machine hôte
    volumes:
      - db_data:/var/lib/mysql  # Les données de la base sont persistantes
    networks:
      - hackathon_network

networks:
  hackathon_network:

volumes:
  db_data:
