version: '3.9'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - hackathon_network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=hackathon
    networks:
      - hackathon_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

networks:
  hackathon_network:

volumes:
  db_data:
